---
# installs docker and docker compose
- hosts: all
  roles:
    - { role: docker}
  vars:
    docker_edition: "ce"
    docker_install_compose: true
    docker_compose_version: "1.13.0"
    docker_initialize_swarm: true
    swarm_iface: eth0
    debug: false


- hosts: docker_swarm_*
  roles:
    - { role: elasticsearch }
  vars:
    es_docker_image: "elasticsearch:5"
    es_data_host_dir: "/elasticsearch/data"
    nginx_docker_image: "nginx:1"
