---
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: "ce"
docker_package: "docker-{{ docker_edition }}"

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "1.13.0"
docker_compose_path: "/usr/local/bin/docker-compose"

# Used only for RedHat/CentOS.
docker_yum_repo_url: "https://download.docker.com/linux/centos/docker-{{ docker_edition }}.repo"
docker_gpg_key: "https://download.docker.com/linux/centos/gpg"

docker_initialize_swarm: true
swarm_iface: "eth0"